[package]
name = "blockchain-network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-preview = "=0.3.0-alpha.18"
futures-timer = "0.4"
log = "0.4"
rand = "0.7"
